### ISSUE TITLE
error when running miniprot_boundary_scorer

### ISSUE THREAD

**Issue by cbortoluzzi** [tomasbruna/miniprot-boundary-scorer#2]
Hi, 

I am trying to run GALBA on a new reference genome assembly. However, after obtaining the alignment with miniprot, I get the following error when running miniprot_boundary_scorer: 

error: Unexpected number of columns in the header. Miniprot PAF header should contain 19 fields
error: Invalid alignment header 

As a result, the miniprot.gff file is not generated. Is there a way around this? 

Many thanks!

Chiara

**Comment by Thamos** [comment]
Hi, I just had the same problem, I think it's because newest miniprot outputs the number of frameshifts and in-frame stop codons in the PAF output ("fs" and "st") which then makes a total of 21 fields instead of 19.
So either use an older version of miniprot (0.11 or older), remove those fields from your alignment file, or edit Alignment.cpp I guess.

**Comment by tomasbruna** [comment]
Thanks for reporting, I'll fix this soon.

**Comment by cbortoluzzi** [comment]
Hi Thamos, 

indeed, the problem is fixed by using an older version of miniprot. Thanks for the suggestion!
